### ISSUE TITLE
critical problem with div

### ISSUE THREAD

**Issue by farteryhr** [vukicevic/crunch#15]
the following test fails on both your current version and my local version.
~~~js
var c=Crunch(true,true);
c.div([7425251],[3725290, 80117760])
//returns [1]
~~~
btw i've tried to modify it like this:
~~~js
//yt = v[0]*268435456 + v[1];
yt = [v[0], v[1]];
//xt = u[i-1]*72057594037927936 + u[i]*268435456 + u[i+1];
xt = [u[i-1], u[i], u[i+1]];
//while (q[i]*yt > xt) { //condition check can fail due to precision problem at 28-bit
while (cmp(mul([q[i]], yt), xt) === 1) { //condition check can fail due to precision problem at 28-bit
~~~
this seems to solve the case at https://github.com/vukicevic/crunch/issues/13, but doesn't help with this one.
sorry i can't fully understand the div code. only i know is that it runs into the loop commented "only cmp as last resort" and q[0]++ which should not happen. maybe problem with the loop condition.
hope this helps.

**Comment by jefft0** [comment]
A possible problem is that JavaScript internally uses a 64-bit floating point number which only has 52 bits precision. In the expression below, ` u[i-1]*72057594037927936` is an 84-bit integer, so there is no representation in the lower 32-bits of the value. This means there is no point in adding the 28-bit value ` u[i+1]`. And some precision from `u[i]*268435456` is also lost. 

    u[i-1]*72057594037927936 + u[i]*268435456 + u[i+1];

Is it necessary to have the full 84-bit precision of this expression for div to work in all cases?

**Comment by jefft0** [comment]
A constructive suggestion: This expression is only used to compute a value `xt` for [comparison on the next line](https://github.com/vukicevic/crunch/blob/85c32295ee84ca727d84781a30946a0012a9b6dd/crunch.js#L427).  So, maybe `xt` itself should be computed using `mul` and `add` and compared with `cmp`. This would keep the full precision.

**Comment by jefft0** [comment]
Oops. I see that in the comparison code linked above you already commented "condition check can fail due to precision problem at 28-bit". Anyway, what do you think about using Crunch arrays and doing the comparison with `cmp`?

**Comment by jefft0** [comment]
I made a pull request to show what I had in mind.

**Comment by vukicevic** [comment]
Looks great! I've merged the request and will push a new version of the lib soon.
