### ISSUE TITLE
Comparison operation inconsistent when byte-lengths differ

### ISSUE THREAD

**Issue by mwh** [vukicevic/crunch#16]
crunch.compare(crunch.parse("2"), crunch.parse("-100")) // -> 1
    crunch.compare(crunch.parse("2"), crunch.parse("-1000")) // -> -1
    crunch.compare(crunch.parse("-256"), crunch.parse("-65535")) // -> 1
    crunch.compare(crunch.parse("-256"), crunch.parse("-65536")) // -> -1

It seems that any multi-byte negative representation is treated as greater than any single-byte representation, and the same for other differing sizes.

**Comment by jefft0** [comment]
In addition to the above problem, two negative values are compared as if they are both positive.

    // Using "raw" mode.
    var x = [1];
    x.negative = true;
    var y = [2];
    y.negative = true;
    console.log(crunch.compare(x, y)); // Should be 1. Prints -1.

**Comment by jefft0** [comment]
Should I do a pull request to fix both the above problems? (It's a pretty simple change to cmp.)

**Comment by vukicevic** [comment]
Please do if you have solved the issue.

Thanks,
Nenad

**Comment by vukicevic** [comment]
Additionally, fixed the parse then compare bug in #26
