### ISSUE TITLE
Web site test suite negative values for compare really aren't negative

### ISSUE THREAD

**Issue by jefft0** [vukicevic/crunch#19]
Related to the not catching the problems in bug #16, the negative values for compare really aren't negative in the web site test suite at http://crunch.js.org/tests/ . For example:

    var x = [5, 10],
        y = [-5, 10];

    crunch.compare(x, y).should.equal(1);

The problem is that crunch.compare treats all input as raw, and in raw mode you have to set y.negative = true. It's just a wild coincidence that the existing tests pass. If it is change to to following, it fails but it shouldn't.

    var x = [5, 10],
        y = [-5, 10, 1];

    crunch.compare(x, y).should.equal(1);

This is because cmp doesn't see y.negative, so it is treated as a positive (greater than x). (The test suite really needs some more test cases.)

Crunch.compare doesn't use transformIn like all the other API methods.
https://github.com/vukicevic/crunch/blob/594aec80062aa0fbcaad6b59a9bf4c6f94bbb2c8/crunch.js#L1103

Should it?

**Comment by vukicevic** [comment]
This is fixed in pull request #26.
