### ISSUE TITLE
a bug in `div`

### ISSUE THREAD

**Issue by Yaffle** [vukicevic/crunch#23]
```
var crunch = new Crunch();
var a = crunch.parse((Math.pow(2, 27) + 1).toString());
var b = crunch.parse(Math.pow(2, 27 + 28).toString());
var c = crunch.div(a, b);
console.log(c); // [1], should be [0]
```
P.S.
https://github.com/vukicevic/crunch/blob/master/crunch.js#L411
```
 d  = u.length - v.length;
```
It seems, some code below this line should not be executed when d < 0.

**Comment by vukicevic** [comment]
Fixed in #29 by short-circuiting the div function to always return 0 when magnitude of x > y, and return 1 when they are equal.
